name: shahganj_superapp
repository: https://github.com/shahganj-online/shahganj-superapp

packages:
  - apps/*
  - packages/*

scripts:
  bootstrap:
    exec: flutter pub get
    description: Run pub get in all workspace packages.
  
  clean:
    exec: flutter pub get
    description: Clean build files and run pub get.

  analyze:
    exec: dart analyze .
    description: Analyze Dart source code.

  test:
    exec: melos exec -- "flutter test"
    description: Run all package tests.

  build_all:
    exec: melos exec --depends-on="build_runner" -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Generate all freezed and serializable Dart code.
